steps:steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', "gcr.io/$PROJECT_ID/example-app:$SHORT_SHA", '.']
  env:
  - 'NODE_ENV=production'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "gcr.io/$PROJECT_ID/example-app:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'example-app', "--image=gcr.io/$PROJECT_ID/example-app:$SHORT_SHA", '--region=europe-central2']